name: Deployment pipeline

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:  
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [12.x]
    #     mongodb-version: [4.0]
        # node-version: [12.x, 14.x]
        # mongodb-version: [4.0, 4.2, 4.4]
    # if: ${{ github.event_name == 'push' }}
    # if: contains(join(github.event.commits.*.message, ', '), '#skip') == 'false'
    steps:
      # - uses: actions/checkout@v2
      # - uses: actions/setup-node@v1
      #   with:
      #     node-version: '12.x'
      # - name: Start MongoDB
      #   uses: supercharge/mongodb-github-action@1.3.0
      #   with:
      #     mongodb-version: '4.0'
          # mongodb-version: '${{ matrix.mongodb-version }}'

      # - name: npm install
      #   run: npm install
      # - name: lint
      #   run: npm run eslint
      # - name: build
      #   run: npm run build
      # - name: test
      #   run: npm run test
      # - name: e2e tests
      #   uses: cypress-io/github-action@v2
        
      #   with:
      #     command: npm run test:e2e
      #     start: npm run start:test
      #     wait-on: http://localhost:3001

        # if: ${{ github.event_name == 'push' }}

      # - uses: 8398a7/action-slack@v3
      #   with:
      #     status: ${{ job.status }}
      #     fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
      #     # fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      #   if: always() # Pick up events even if the job fails or is canceled.

      # - name: Check the deployed service URL
      #   uses: jtalk/url-health-check-action@v1.2
      #   with:
      #     # Check the following URLs one by one sequentially
      #     url: https://full-stack-pokedex-2020dec29.herokuapp.com/health
      #     # Follow redirects, or just report success on 3xx status codes
      #     follow-redirect: no # Optional, defaults to "no"
      #     # Fail this action after this many failed attempts
      #     max-attempts: 3 # Optional, defaults to 1
      #     # Delay between retries
      #     retry-delay: 5s # Optional, only applicable to max-attempts > 1

 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: jctaveras/heroku-deploy@v1.0.0  # use the latest version of the action
        with:
          email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
          app_name: ${{ secrets.HEROKU_APP_NAME }} # you aplication name
          dockerfile_path: ./ # set the path to the folder wher the Dokerfile is located
          # options: '' # Docker Build Options
          # formation: '' # Docker Dyno Formation. By default is web

      # - uses: actions/checkout@v2
      # - uses: akhileshns/heroku-deploy@v3.8.8 # This is the action
      #   with:
      #     heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      #     heroku_app_name: "docker-hy-github-io-3-2-part3" #Must be unique in Heroku
      #     heroku_email: "tranluc2007@gmail.com"
      #     # healthcheck: https://your-own-pipeline-bloglist.herokuapp.com/health
      #     # checkstring: ok
      #     rollbackonhealthcheckfailed: true
      
      # - name: Bump version and push tag
      #   uses: anothrNick/github-tag-action@1.33.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}